version: "3.9"

name: lol_twitch_vods
services:
  db:
    container_name: lol_twitch_vods_postgresql
    platform: linux/x86_64
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lol_twitch_vods
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  localstack:
    container_name: "lol_twitch_vods_localstack"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=1
    volumes:
      - "./.docker-volumes/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data:
