// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lol_twitch_vods_api.Data;

#nullable disable

namespace lol_twitch_vods_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260201043703_AddPuuidColumnToMatch")]
    partial class AddPuuidColumnToMatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("lol_twitch_vods_api.Models.LolAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("puuid");

                    b.Property<int>("Server")
                        .HasColumnType("integer")
                        .HasColumnName("server");

                    b.Property<Guid>("StreamerId")
                        .HasColumnType("uuid")
                        .HasColumnName("streamer_id");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_lol_accounts");

                    b.HasIndex("StreamerId");

                    b.ToTable("lol_accounts");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("GameEndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("game_end_date_time");

                    b.Property<DateTime>("GameStartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("game_start_date_time");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("puuid");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.ToTable("matches");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<string>("ChampionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("champion_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer")
                        .HasColumnName("deaths");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Kills")
                        .HasColumnType("integer")
                        .HasColumnName("kills");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("MatchStartVod")
                        .HasColumnType("text")
                        .HasColumnName("match_start_vod");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("puuid");

                    b.Property<Guid?>("StreamerId")
                        .HasColumnType("uuid")
                        .HasColumnName("streamer_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("VodId")
                        .HasColumnType("bigint")
                        .HasColumnName("vod_id");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean")
                        .HasColumnName("win");

                    b.HasKey("Id")
                        .HasName("pk_participants");

                    b.HasIndex("MatchId");

                    b.HasIndex("StreamerId");

                    b.ToTable("participants");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.Streamer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_image");

                    b.Property<string>("TwitchId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("twitch_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_streamers");

                    b.ToTable("streamers");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.LolAccount", b =>
                {
                    b.HasOne("lol_twitch_vods_api.Models.Streamer", "Streamer")
                        .WithMany("LolAccounts")
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lol_accounts_streamers_streamer_id");

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.Participant", b =>
                {
                    b.HasOne("lol_twitch_vods_api.Models.Match", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participants_matches_match_id");

                    b.HasOne("lol_twitch_vods_api.Models.Streamer", "Streamer")
                        .WithMany("Participants")
                        .HasForeignKey("StreamerId")
                        .HasConstraintName("fk_participants_streamers_streamer_id");

                    b.Navigation("Match");

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.Match", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.Streamer", b =>
                {
                    b.Navigation("LolAccounts");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
