// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lol_twitch_vods_api.Data;

#nullable disable

namespace lol_twitch_vods_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("lol_twitch_vods_api.Models.LolAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Server")
                        .HasColumnType("integer");

                    b.Property<int>("StreamerId")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId");

                    b.ToTable("LolAccounts");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GameEndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GameStartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<string>("ChampionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MatchId1")
                        .HasColumnType("integer");

                    b.Property<string>("MatchStartVod")
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StreamerId")
                        .HasColumnType("integer");

                    b.Property<long>("VodId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MatchId1");

                    b.HasIndex("StreamerId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.Streamer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TwitchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Streamers");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.LolAccount", b =>
                {
                    b.HasOne("lol_twitch_vods_api.Models.Streamer", "Streamer")
                        .WithMany("LolAccounts")
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.Participant", b =>
                {
                    b.HasOne("lol_twitch_vods_api.Models.Match", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId1");

                    b.HasOne("lol_twitch_vods_api.Models.Streamer", "Streamer")
                        .WithMany("Participants")
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.Match", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("lol_twitch_vods_api.Models.Streamer", b =>
                {
                    b.Navigation("LolAccounts");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
